language: ruby

notifications:
  email: false

rvm:
  - 2.0.0
  - 2.1.1
  - jruby-19mode
  - ruby-head

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: ruby-head

gemfile:
  - gemfiles/activemodel-4
  - gemfiles/activemodel-3-2
  - gemfiles/standalone
